apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-history-server
  namespace: spark-operator
spec:
  selector:
    matchLabels:
      app: spark-history-server
  replicas: 1
  template:
    metadata:
      name: spark-history-server
      labels:
        app: spark-history-server
    spec:
      volumes:
      - name: "test-volume"
        hostPath:
          path: "/tmp"
          type: Directory
      - name: gcp-cred
        secret:
          secretName: google-sa-key
      containers:
        - name: spark-history-server
          image: mesodiar/spark-k8s-gcs:v3
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
          volumeMounts:
            - name: "test-volume"
              mountPath: "/tmp"
            - name: "gcp-cred"
              mountPath: "/creds"
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: google-sa-key
                  key: path
          command:
            - /opt/spark/bin/spark-class
            - -Dspark.eventLog.enabled=true
            - -Dspark.hadoop.google.cloud.auth.service.account.json.keyfile=/creds/google_sa_key.json
            - -Dspark.history.fs.logDirectory=gs://spark-poc-logs/
            - -Dspark.eventLog.dir=gs://spark-poc-logs
            - -Divy.cache.dir=/tmp
            - -Divy.home=/tmp
            - org.apache.spark.deploy.history.HistoryServer
          ports:
            - name: http
              protocol: TCP
              containerPort: 18080 
          readinessProbe:
            timeoutSeconds: 4
            httpGet:
              path: /
              port: http
          livenessProbe:
            timeoutSeconds: 4
            httpGet:
              path: /
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: spark-history-service
  namespace: spark-operator
spec:
  selector:
    app: spark-history-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 18080